[build]
  command = "npx prisma generate && npx prisma db push && node prisma/seed.js && next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"
  NEXT_PRIVATE_LOCAL_DIR = ".next"
